version: '3'
services:
  # proxy-onhyang-admin:
  #   image: nginx:latest
  #   container_name: proxy
  #   restart: unless-stopped
  #   volumes:
  #     - ./proxy/nginx.conf:/etc/nginx/nginx.conf
  #     - ./data/proxy:/var/log/nginx/
  #   environment:
  #     TZ: 'UTC'
  #   ports:
  #     - 80:80

  coin-tracker:
    build:
      context: ./coin-tracker
      dockerfile: Dockerfile.dev
    container_name: coin-tracker
    volumes:
      - /usr/src/web/.yarn
      - ./coin-tracker/src:/usr/src/web/src
      - ./data/web/logs:/usr/src/web/logs
    ports:
      - '3000:3000'
    expose:
      - '3000'
    env_file:
      - ./coin-tracker/.env.development
    platform: linux/x86_64
    mem_limit: 8g
    mem_reservation: 8g
    memswap_limit: 8g
