FROM node:16 AS builder

WORKDIR /usr/src/app

# 의존성 설치
COPY ./package.json ./

# Set yarn berry
RUN yarn set version berry

# Set TS depending on yarn-berry
RUN yarn plugin import workspace-tools

# yarn install
COPY yarn.lock ./
RUN yarn
COPY . .

# build
# CMD ["yarn", "run", "build"]

FROM node:16-alpine
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app ./
CMD [ "yarn" ,"start"]
EXPOSE 3000